spring:
  cloud:
    gcp:
      firestore:
        project-id: your-project-id
        credentials:
          location: file:/Users/paulolphert/git_repo/MOTBOOKINGREMINDERAPPKEY/motbookingreminder-firebase-adminsdk-3yaxx-ef71a03334.json