spring:
  cloud:
    gcp:
      firestore:
        project-id: motbookingreminder
        credentials:
          location: file:/Users/paulolphert/git_repo/MOTBOOKINGREMINDERAPPKEY/motbookingreminder-firebase-adminsdk-3yaxx-ef71a03334.json